services:
  web:
    container_name: front-page-absolute
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.front-page-absolute.rule: Host(`${TRAFIK_HOST}`)

    # Disable direct access - all access will be via traefik
    ports: !reset []

networks:
  traefik:
    external: true
